#+TITLE: YACLOMP

Yet Another Clojure Org-Mode Parser

* Why?

Because I like writing in [[http://orgmode.org/][Org Mode]] a lot better than Markdown (or
Textile or ...).  /Work in progress.  Do not pass
go.  Do not collect $200./

* Why [[https://github.com/gmorpheme/organum][Another]] [[https://github.com/nakkaya/static][One]]?

- I want to use (and get better at) [[https://github.com/Engelberg/instaparse][Instaparse]];
- I want to have a quick feedback / improvement cycle, since I plan to
  use this for my own projects.

* Status

I just started this.

* Disclaimer

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
